version: "3"
services:
  bolt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
